import type { Crypto } from './types.ts';

export const REVOLUT_CRYPTOS: Crypto[] = [
  { symbol: 'BTC', id: 'bitcoin', name: 'Bitcoin' },
  { symbol: 'ETH', id: 'ethereum', name: 'Ethereum' },
  { symbol: 'SOL', id: 'solana', name: 'Solana' },
  { symbol: 'XRP', id: 'ripple', name: 'XRP' },
  { symbol: 'DOGE', id: 'dogecoin', name: 'Dogecoin' },
  { symbol: 'ADA', id: 'cardano', name: 'Cardano' },
  { symbol: 'DOT', id: 'polkadot', name: 'Polkadot' },
  { symbol: 'MATIC', id: 'matic-network', name: 'Polygon' },
  { symbol: 'LINK', id: 'chainlink', name: 'Chainlink' },
  { symbol: 'AVAX', id: 'avalanche-2', name: 'Avalanche' },
  { symbol: 'SHIB', id: 'shiba-inu', name: 'Shiba Inu' },
  { symbol: 'UNI', id: 'uniswap', name: 'Uniswap' },
  { symbol: 'LTC', id: 'litecoin', name: 'Litecoin' },
  { symbol: 'BCH', id: 'bitcoin-cash', name: 'Bitcoin Cash' },
  { symbol: 'ATOM', id: 'cosmos', name: 'Cosmos' },
  { symbol: 'XLM', id: 'stellar', name: 'Stellar' },
  { symbol: 'ALGO', id: 'algorand', name: 'Algorand' },
  { symbol: 'VET', id: 'vechain', name: 'VeChain' },
  { symbol: 'FIL', id: 'filecoin', name: 'Filecoin' },
  { symbol: 'ICP', id: 'internet-computer', name: 'Internet Computer' },
  { symbol: 'NEAR', id: 'near', name: 'NEAR Protocol' },
  { symbol: 'AAVE', id: 'aave', name: 'Aave' },
  { symbol: 'GRT', id: 'the-graph', name: 'The Graph' },
  { symbol: 'SAND', id: 'the-sandbox', name: 'The Sandbox' },
  { symbol: 'MANA', id: 'decentraland', name: 'Decentraland' },
  { symbol: 'AXS', id: 'axie-infinity', name: 'Axie Infinity' },
  { symbol: 'HBAR', id: 'hedera-hashgraph', name: 'Hedera' },
  { symbol: 'THETA', id: 'theta-token', name: 'Theta Network' },
  { symbol: 'XTZ', id: 'tezos', name: 'Tezos' },
  { symbol: 'EOS', id: 'eos', name: 'EOS' },
  { symbol: 'BAT', id: 'basic-attention-token', name: 'BAT' },
  { symbol: 'ZRX', id: '0x', name: '0x Protocol' },
  { symbol: 'MKR', id: 'maker', name: 'Maker' },
  { symbol: 'COMP', id: 'compound-governance-token', name: 'Compound' },
  { symbol: 'YFI', id: 'yearn-finance', name: 'yearn.finance' },
  { symbol: 'SNX', id: 'havven', name: 'Synthetix' },
  { symbol: 'CRV', id: 'curve-dao-token', name: 'Curve DAO' },
  { symbol: 'SUSHI', id: 'sushi', name: 'SushiSwap' },
  { symbol: '1INCH', id: '1inch', name: '1inch' },
  { symbol: 'ENJ', id: 'enjincoin', name: 'Enjin Coin' },
  { symbol: 'CHZ', id: 'chiliz', name: 'Chiliz' },
  { symbol: 'ANKR', id: 'ankr', name: 'Ankr' },
  { symbol: 'FLOW', id: 'flow', name: 'Flow' },
  { symbol: 'ONE', id: 'harmony', name: 'Harmony' },
  { symbol: 'GALA', id: 'gala', name: 'Gala' },
  { symbol: 'LRC', id: 'loopring', name: 'Loopring' },
  { symbol: 'FTM', id: 'fantom', name: 'Fantom' },
  { symbol: 'STORJ', id: 'storj', name: 'Storj' },
  { symbol: 'NMR', id: 'numeraire', name: 'Numeraire' },
  { symbol: 'BNT', id: 'bancor', name: 'Bancor' },
];
